// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Home | Project → Images*
 */
export interface HomeProjectDocumentDataImagesItem {
  /**
   * Image field in *Home | Project → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_project.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Home | Project documents
 */
interface HomeProjectDocumentData {
  /**
   * Name field in *Home | Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Date field in *Home | Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: home_project.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Description field in *Home | Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Home | Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_project.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link | Name field in *Home | Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_project.link_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_name: prismic.KeyTextField;

  /**
   * Images field in *Home | Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_project.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<HomeProjectDocumentDataImagesItem>>;

  /**
   * Vidéo field in *Home | Project*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: home_project.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Home | Project document from Prismic
 *
 * - **API ID**: `home_project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomeProjectDocumentData>,
    "home_project",
    Lang
  >;

/**
 * Item in *Page | Home → Section | Keywords*
 */
export interface PageHomeDocumentDataSectionKeywordsItem {
  /**
   * Name field in *Page | Home → Section | Keywords*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_home.section_keywords[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Speed field in *Page | Home → Section | Keywords*
   *
   * - **Field Type**: Number
   * - **Placeholder**: For every full screen height scrolled, the element will shift horizontally by X% of viewport width
   * - **API ID Path**: page_home.section_keywords[].speed
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  speed: prismic.NumberField;

  /**
   * Custom CSS field in *Page | Home → Section | Keywords*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_home.section_keywords[].custom_css
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_css: prismic.KeyTextField;
}

/**
 * Item in *Page | Home → Section | Projects*
 */
export interface PageHomeDocumentDataSectionProjectsItem {
  /**
   * Project field in *Page | Home → Section | Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page_home.section_projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"home_project">;
}

/**
 * Content for Page | Home documents
 */
interface PageHomeDocumentData {
  /**
   * Section | Keywords field in *Page | Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page_home.section_keywords[]
   * - **Tab**: Keywords
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  section_keywords: prismic.GroupField<
    Simplify<PageHomeDocumentDataSectionKeywordsItem>
  > /**
   * Section | Projects field in *Page | Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page_home.section_projects[]
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  section_projects: prismic.GroupField<
    Simplify<PageHomeDocumentDataSectionProjectsItem>
  >;
}

/**
 * Page | Home document from Prismic
 *
 * - **API ID**: `page_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PageHomeDocumentData>,
    "page_home",
    Lang
  >;

export type AllDocumentTypes = HomeProjectDocument | PageHomeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeProjectDocument,
      HomeProjectDocumentData,
      HomeProjectDocumentDataImagesItem,
      PageHomeDocument,
      PageHomeDocumentData,
      PageHomeDocumentDataSectionKeywordsItem,
      PageHomeDocumentDataSectionProjectsItem,
      AllDocumentTypes,
    };
  }
}
